Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-07, with the labels that each got.

#432 remove excess python path setting
  ci/dockerfile.ci
  docker/dockerfile.merlin
Labels: ci

#430 Update README with installation steps
  README.md
Labels: documentation

#439 Add jupyter ENVs in case launching container with normal user
  docker/dockerfile.merlin
Labels: enhancement, ci

#441 Add pytorch tritonserver backend to ci dockerfile
  ci/dockerfile.ci
  docker/dockerfile.merlin
Labels: bug, ci

#390 remove extra CMD from containers
  docker/dockerfile.ctr
  docker/dockerfile.tf
  docker/dockerfile.torch
Labels: bug, ci

#434 Switch over HDFS build/install scripts
  docker/build-hadoop.sh
  docker/dockerfile.ctr
  docker/install-hadoop.sh
Labels: enhancement, ci

#444 Refactor the container test script to run all the SW checks, unit tests, or integration tests before failing
  ci/integration_tests.sh
  ci/software_check.sh
  ci/test_container.sh
  ci/unit_tests.sh
Labels: chore

#445 Fix typo in CI script file name
  ci/test_container.sh
Labels: bug

#469 added fiddle to container for models testing
  .github/workflows/docs-build.yaml
  docker/dockerfile.merlin
Labels: chore, ci

#470 Add wandb
  docker/dockerfile.merlin
Labels: chore, ci

#438 Adds integration tests to Merlin Models
  ci/integration_tests.sh
Labels: ci

#466 Remove unnecessary dependencies from docs builds
  docs/requirements-doc.txt
  docs/source/conf.py
Labels: chore

#487 fixes in the PoC first notebook
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
Labels: enhancement, example
