Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-11, with the labels that each got.

#717 fix: Update HugeCTR version to 4.1.1
  docs/data.json
Labels: documentation

#718 create resilient directory rm
  docker/dockerfile.torch
Labels: bug, chore, ci

#713 add in reinstall for dask and distributed after feast install
  ci/test_integration.sh
Labels: bug, chore, ci

#721 docs: Remove SM from the support matrix
  docs/table_config.yaml
Labels: documentation

#722 adding dataloader repo to dockerfile
  docker/dockerfile.merlin
Labels: bug, chore, ci

#724 Pass mpi environment variable to tox
  tox.ini
Labels: ci

#725 adding in instructions from the jenkins dockerfile to keep in one place
  ci/dockerfile.ci
Labels: chore, ci

#723 docs: Add configuration for SEO
  docs/Makefile
  docs/source/conf.py
Labels: documentation

#715 docs: semver to calver banner
  docs/source/_static/css/custom.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#727 adding new metric loss_batch from merlin models
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: bug, chore, ci

#692 Add example notebook for training and inference on Sagemaker
  examples/sagemaker-tensorflow/README.md
  examples/sagemaker-tensorflow/build_and_push_image.sh
  examples/sagemaker-tensorflow/container/Dockerfile
  examples/sagemaker-tensorflow/sagemaker-merlin-tensorflow.ipynb
  examples/sagemaker-tensorflow/train.py
Labels: examples

#726 anchor xgboost to 1.6.2 to make tests pass
  docker/dockerfile.merlin
Labels: bug, chore, ci

#729 Increase timeout of multi-stage notebook test from 120 to 180
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: ci

#728 add dataloader unit testing to container run
  ci/container_unit.sh
Labels: chore, ci

#735 add required dataloader dependency to run unit tests for dataloader
  docker/dockerfile.merlin
Labels: bug, chore, ci

#738 Reduce docs size
  .github/workflows/docs-build.yaml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-sched-rebuild.yaml
  docs/requirements-doc.txt
  docs/source/conf.py
Labels: chore, skip-changelog

#739 Restrict `cmake<3.25.0` to avoid an issue finding CUDA toolkit
  docker/dockerfile.merlin
Labels: bug, chore, ci

#740 Update `dockerfile.ci` to find the NVT dev requirements file
  ci/dockerfile.ci
Labels: bug, chore, ci

#734 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: chore, ci, gpuCI-test-this

#748 chore: Add deps for testing
  docs/requirements-doc.txt
Labels: chore, skip-changelog

#751 Adjust package paths for `torch`, `numpy`, `numba` in Torch Docker image
  docker/dockerfile.torch
Labels: chore, ci
