Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-12, with the labels that each got.

#753 Replace sklearn by scikit-learn in pip install
  docker/dockerfile.merlin
Labels: chore, ci

#754 Add SageMaker example to docs
  docs/source/conf.py
  docs/source/toc.yaml
  examples/sagemaker-tensorflow/sagemaker-merlin-tensorflow.ipynb
  tox.ini
Labels: documentation

#742 Migrate the legacy examples to the Merlin repo
  .gitignore
  examples/legacy/README.md
  examples/legacy/getting-started-movielens/01-Download-Convert.ipynb
  examples/legacy/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-TF.ipynb
  examples/legacy/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/legacy/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/legacy/getting-started-movielens/README.md
  examples/legacy/getting-started-movielens/imgs/triton-tf.png
  examples/legacy/getting-started-movielens/inference-HugeCTR/.ipynb_checkpoints/Training-with-HugeCTR-checkpoint.ipynb
  examples/legacy/imgs/dask-dataframe.svg
  examples/legacy/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-TensorFlow.ipynb
  examples/legacy/multi-gpu-movielens/README.md
  examples/legacy/multi-gpu-movielens/hvd_wrapper.sh
  examples/legacy/multi-gpu-movielens/tf_trainer.py
  examples/legacy/multi-gpu-toy-example/multi-gpu_dask.ipynb
  examples/legacy/scaling-criteo/01-Download-Convert.ipynb
  examples/legacy/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/legacy/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/legacy/scaling-criteo/03-Training-with-TF.ipynb
  examples/legacy/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/legacy/scaling-criteo/04-Triton-Inference-with-TF.ipynb
  examples/legacy/scaling-criteo/README.md
  examples/legacy/scaling-criteo/docker-compose-fastai.yml
  examples/legacy/scaling-criteo/docker-compose-hugectr.yml
  examples/legacy/scaling-criteo/docker-compose-tf.yml
  examples/legacy/scaling-criteo/imgs/dask-dataframe.svg
  examples/legacy/scaling-criteo/imgs/triton-hugectr.png
  examples/legacy/scaling-criteo/imgs/triton-tf.png
  examples/legacy/tensorflow/README.md
  examples/legacy/tensorflow/TFRecords-To-Parquet.ipynb
  examples/legacy/tensorflow/accelerating-tensorflow.ipynb
  examples/legacy/tensorflow/callbacks.py
  examples/legacy/tensorflow/docker/Dockerfile
  examples/legacy/tensorflow/docker/requirements.txt
  examples/legacy/tensorflow/imgs/cpu-native_vs_gpu-native.PNG
  examples/legacy/tensorflow/imgs/cpu-native_vs_gpu-native_vs_gpu-accelerated.PNG
  examples/legacy/tensorflow/imgs/cpu-native_vs_gpu-native_vs_gpu-accelerated_vs_gpu-native-mp.PNG
  examples/legacy/tensorflow/imgs/cpu-native_vs_gpu-native_vs_gpu-accelerated_vs_gpu-native-mp_vs_gpu-accelerated-mp.PNG
  examples/legacy/tensorflow/imgs/full-precision-matmul.PNG
  examples/legacy/tensorflow/imgs/gpu-accelerated-trace.PNG
  examples/legacy/tensorflow/imgs/gpu-native-trace-zoom.PNG
  examples/legacy/tensorflow/imgs/gpu-native-trace.PNG
  examples/legacy/tensorflow/imgs/mixed-precision-matmul.PNG
  tests/conftest.py
  tests/unit/examples/test_z_legacy_notebooks.py
Labels: chore

#756 Review Criteo Examples and Added Unittest
  examples/README.md
  examples/scaling-criteo/01-Download-Convert.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/03-Training-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/README.md
  tests/unit/examples/test_scaling_criteo_merlin_models_hugectr.py
Labels: examples

#757 Remove legacy Criteo examples
  examples/legacy/scaling-criteo/01-Download-Convert.ipynb
  examples/legacy/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/legacy/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/legacy/scaling-criteo/03-Training-with-TF.ipynb
  examples/legacy/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/legacy/scaling-criteo/04-Triton-Inference-with-TF.ipynb
  examples/legacy/scaling-criteo/README.md
  examples/legacy/scaling-criteo/docker-compose-fastai.yml
  examples/legacy/scaling-criteo/docker-compose-hugectr.yml
  examples/legacy/scaling-criteo/docker-compose-tf.yml
  examples/legacy/scaling-criteo/imgs/dask-dataframe.svg
  examples/legacy/scaling-criteo/imgs/triton-hugectr.png
  examples/legacy/scaling-criteo/imgs/triton-tf.png
  tests/unit/examples/test_scaling_criteo_optimize_notebook.py
  tests/unit/examples/test_z_legacy_notebooks.py
Labels: examples

#758 Inconsistent order of columns in getting-started-movielens tutorial
  docs/source/conf.py
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-TF.ipynb
Labels: documentation

#761 fixes support library lookups for torch
  docker/dockerfile.torch
Labels: ci

#763 Update hps_tf folder name
  docker/dockerfile-nightly.merlin
  docker/dockerfile.tf
Labels: ci

#762 add gcp label to jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: chore, ci, gpuCI-test-this

#750 Bump `treelite` to 2.4.0 to match with Triton 22.11
  docker/dockerfile.merlin
Labels: chore, ci

#772 Replace `ensemble_model` with `executor_model`
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  examples/sagemaker-tensorflow/sagemaker-merlin-tensorflow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: ci

#770 Pin pyarrow version for integration tests
  ci/test_integration.sh
Labels: ci

#773 Remove data manipulation in integration test and run the first notebo…
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: chore, ci, 22.12

#778 Replace next(iter(loader)) with loader.peek()
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-TF.ipynb
Labels: enhancement, examples, ci

#780 save env var for systems test
  ci/container_unit.sh
Labels: chore, ci

#781 update dockerfile merlin base container
  docker/dockerfile.merlin
Labels: chore, ci
