Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-09, with the labels that each got.

#582 Second fix
  ci/test_integration.sh
Labels: chore, ci

#583 Rearrange testing for faster feedback
  ci/test_container.sh
Labels: chore, ci

#584 Include a SM80 enabled version of faiss on merlin-base container
  docker/dockerfile.merlin
Labels: ci

#587 Fixes for faiss install
  docker/dockerfile.merlin
Labels: ci

#590 Install numpy for building faiss
  docker/dockerfile.merlin
Labels: ci

#596 Add a "New Functionality" section to the Roadmap issue template
  .github/ISSUE_TEMPLATE/roadmap.md
Labels: documentation, chore

#601 anchor Tf version
  docker/dockerfile.tf
Labels: chore, ci

#603 Args mv
  docker/dockerfile.merlin
Labels: chore, ci

#615 Add dockerfile for nightly builds
  docker/dockerfile-nightly.merlin
Labels: ci

#616 Add dock nite
  docker/dockerfile-nightly.merlin
Labels: ci

#617 Adding git pull command to nightly docker to ensure latest commit
  docker/dockerfile-nightly.merlin
Labels: bug, ci

#620 Update ci container to use nightly base container
  ci/dockerfile.ci
Labels: ci

#623 Add a `tox` config file
  tox.ini
Labels: chore, ci

#624 Remove lint env from tox config
  setup.py
  tox.ini
Labels: chore, ci

#619 Revert to working tritonserver call in notebook using testbooks
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: chore, ci

#625 anchor tf version to avoid errors in 2.10.0 libnvinfer look ups
  ci/dockerfile.ci
Labels: ci

#621 modify multi-stage deployment nbs wrt recent changes in systems 
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
Labels: enhancement, examples

#626 Address virtual dev review comments
  README.md
  docs/source/containers.rst
  docs/source/index.rst
  docs/source/toc.yaml
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/README.md
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/03-Training-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: documentation

#627 Update multi-stage deployment notebooks and integration test
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: enhancement, help wanted, ci

#622 Update paths using `BASE_DIR` in multi-stage notebook to handle non-default value
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
Labels: chore, ci

#629 Add Dropna to remove nulls in the dataset that creates error in the integration test of multi-stage deployment nb
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: enhancement, ci

#630 Increase timeout of unit test for second multi-stage notebook
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: ci

#632 Adding hugectr to nightly build dockerfile
  docker/dockerfile-nightly.merlin
Labels: ci
