Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-06, with the labels that each got.

#351 Refactor SMX for blossom
  .github/workflows/docs-ci.yaml
  .github/workflows/docs-smx-data.yaml
  docs/README.md
  docs/extractor.py
  docs/requirements-doc.txt
  docs/test_extractor.py
Labels: chore

#381 Add a GA workflow that requires labels on PR's
  .github/workflows/require-label.yaml
Labels: ci

#382 Add nvt backend back into containers
  .gitignore
  docker/dockerfile.merlin
  docker/inference/dockerfile.ctr
  docker/training/dockerfile.ctr
Labels: bug

#383 Rm old docker
  docker/inference/dockerfile.ctr
  docker/inference/dockerfile.tf
  docker/inference/dockerfile.torch
  docker/training/dockerfile.ctr
  docker/training/dockerfile.tf
  docker/training/dockerfile.torch
Labels: invalid, ci

#386 Add matplotlib to torch container
  docker/dockerfile.torch
Labels: bug, ci

#389 updates from entrypoint and cupy cuda116
  docker/dockerfile.merlin
Labels: bug, ci

#387 fix poc nbs and move poc unit test
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: enhancement, example

#392 Add skip checks to examples tests
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: bug, ci

#379 Document the change to three containers
  .pre-commit-config.yaml
  Release.md
  ci/versions.py
  docker/README.md
  docs/README.md
  docs/data.json
  docs/smx2rst.py
  docs/source/containers.rst
  docs/source/support_matrix/index.rst
  docs/source/support_matrix/support_matrix_merlin_hugectr.rst
  docs/source/support_matrix/support_matrix_merlin_inference.rst
  docs/source/support_matrix/support_matrix_merlin_pytorch.rst
  docs/source/support_matrix/support_matrix_merlin_pytorch_inference.rst
  docs/source/support_matrix/support_matrix_merlin_pytorch_training.rst
  docs/source/support_matrix/support_matrix_merlin_tensorflow.rst
  docs/source/support_matrix/support_matrix_merlin_tensorflow_inference.rst
  docs/source/support_matrix/support_matrix_merlin_tensorflow_training.rst
  docs/source/support_matrix/support_matrix_merlin_training.rst
  docs/table_config.yaml
  examples/README.md
  examples/getting-started-movielens/01-Download-Convert.ipynb
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/scaling-criteo/01-Download-Convert.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/docker-compose-hugectr.yml
  examples/scaling-criteo/docker-compose-tf.yml
  setup.cfg
Labels: documentation

#384 Add sok test new
  ci/test_container.sh
  docker/dockerfile.tf
Labels: ci

#391 Restrict tritonclient to 2.22.0
  docker/dockerfile.merlin
Labels: dependencies

#396 Update test_container.sh script
  ci/test_container.sh
Labels: ci

#398 Inline hugectr container tests
  ci/test_container.sh
Labels: ci

#400 Update URLs for Criteo dataset
  examples/scaling-criteo/01-Download-Convert.ipynb
Labels: documentation

#401 Always run NVT integration tests
  ci/test_container.sh
Labels: ci

#415 Add run timestamp to data
  .pylintrc
  docs/README.md
  docs/extractor.py
Labels: documentation

#399 Add NGC overview descriptions for our containers
  docker/ngc_overview_hugectr.md
  docker/ngc_overview_pytorch.md
  docker/ngc_overview_tensorflow.md
Labels: documentation

#416 Fix failing treelite install
  docker/dockerfile.merlin
Labels: ci

#417 Remove stale doc reviews
  .github/workflows/docs-remove-stale-reviews.yaml
Labels: chore

#427 Fix extraction of compressed size
  docs/extractor.py
  docs/test_extractor.py
Labels: skip-changelog
