Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-08, with the labels that each got.

#450 Add tests in the Merlin repo to the CI test scripts
  ci/integration_tests.sh
  ci/unit_tests.sh
Labels: chore

#483 Convert the default text in the roadmap issue template to comments
  .github/ISSUE_TEMPLATE/roadmap.md
Labels: chore

#380 Update Criteo Example with Merlin Models and Merlin Systems
  README.md
  examples/README.md
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-FastAI.ipynb
  examples/scaling-criteo/03-Training-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/03-Training-with-TF.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-TF.ipynb
  examples/scaling-criteo/README.md
  examples/scaling-criteo/docker-compose-fastai.yml
  examples/scaling-criteo/docker-compose-hugectr.yml
  examples/scaling-criteo/docker-compose-tf.yml
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: documentation, example

#440 docs: Readability improvements
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  examples/README.md
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
Labels: documentation

#498 Get TF version from Python and not Pip
  docs/extractor.py
Labels: documentation

#486 Downgrade onnxruntime due to security issue of mpmath
  docker/dockerfile.ctr
Labels: dependencies

#518 Fix nightly container builds
  tests/conftest.py
Labels: bug

#502 Changes for hugectr
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: enhancement

#520 Install Feast/Faiss before running Merlin integration tests
  ci/container_integration.sh
  ci/container_software.sh
  ci/container_unit.sh
  ci/test_container.sh
  ci/test_integration.sh
Labels: chore, ci

#521 Make integration test script executable
  ci/test_integration.sh
Labels: chore, ci

#523 Remove duplicate CMake installs
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: chore, ci

#533 Pin `fsspec==22.5.0` directly in the Merlin base image
  docker/dockerfile.merlin
Labels: chore, ci

#532 install tox in base image
  ci/dockerfile.ci
Labels: chore, ci

#537 Mark "scaling Criteo" notebook to be skipped without TF
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: chore, ci

#524 Install CMake in Merlin base image (instead of copying from build)
  docker/dockerfile.merlin
Labels: chore, ci

#538 Revert CMake changes
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: chore, ci

#541 Skip multi-stage example integration test (for now)
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: chore, ci

#543 Skip the multi-stage example notebook (for now)
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: chore, ci

#544 Fix integration test and update NB
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: bug

#549 Remove dependencies of hugectr & install hps tf plugin to merlin-tf
  docker/dockerfile.ctr
  docker/dockerfile.tf
Labels: chore

#558 Update the Merlin repos in the CI image build
  ci/dockerfile.ci
Labels: chore, ci

#556 update base dockerfile
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
  docker/dockerfile.torch
Labels: ci

#559 Fix unit scaling criteo inference serving
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: bug, chore, breaking, ci

#560 Update Merlin libs graphic
  docs/images/recommender-systems-dev-web-850.svg
Labels: documentation

#561 Add skip tf crit unit
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: chore, ci

#563 Docker fix
  docker/dockerfile.merlin
Labels: ci

#564 Docker edit
  docker/dockerfile.merlin
Labels: chore, ci

#566 Add numpy anchor version after all package building and updates
  docker/dockerfile.merlin
Labels: breaking, ci

#565 Add hadoop envs
  docker/dockerfile.ctr
  docker/dockerfile.tf
Labels: ci, dependencies

#569 Update Logos of all examples
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  examples/getting-started-movielens/01-Download-Convert.ipynb
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/scaling-criteo/01-Download-Convert.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/03-Training-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
Labels: examples

#577 Fix int + unit tests
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: chore, ci

#578 Fix int test
  ci/test_integration.sh
Labels: chore, breaking, ci

#579 Reduce the size of synthetic data used in Criteo test
  tests/unit/examples/test_scaling_criteo_merlin_models.py
Labels: chore, ci

#581 Fix ci order
  ci/container_integration.sh
Labels: chore, breaking, ci

#580 Update triage github actions workflow
  .github/workflows/triage.yml
Labels: ci
