Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-05, with the labels that each got.

#261 Copy hadoop
  docker/inference/dockerfile.ctr
  docker/training/dockerfile.ctr
Labels: bug

#262 Rm hadoop xtra
  docker/inference/build-hadoop.sh
  docker/inference/install-hadoop.sh
  docker/training/build-hadoop.sh
  docker/training/install-hadoop.sh
Labels: enhancement

#251 docs: Use MyST and sphinx-external-toc
  README.md
  docs/requirements-doc.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/support_matrix/index.rst
  docs/source/toc.yaml
  examples/Building-and-deploying-multi-stage-RecSys/README.md
  examples/README.md
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/getting-started-movielens/README.md
  examples/index.rst
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/README.md
Labels: documentation

#288 Add Unit test for Building and deploying multi-stage Recsys nbs
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  tests/examples/test_building_deploying_multi_stage_RecSys.py
Labels: inference, roadmap

#290 docs: Tooling and automation for support matrix
  .github/workflows/docs-ci.yaml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/docs-smx-data.yaml
  .gitignore
  .pylintrc
  ci/versions.py
  docs/README.md
  docs/data.json
  docs/extractor.py
  docs/fixtures/data.json
  docs/fixtures/sample.json
  docs/fixtures/sample_after.json
  docs/requirements-doc.txt
  docs/smx2rst.py
  docs/snippets.yaml
  docs/source/conf.py
  docs/source/generated/nvcr.io-nvidia-merlin-merlin-inference.rst
  docs/source/generated/nvcr.io-nvidia-merlin-merlin-pytorch-inference.rst
  docs/source/generated/nvcr.io-nvidia-merlin-merlin-pytorch-training.rst
  docs/source/generated/nvcr.io-nvidia-merlin-merlin-tensorflow-inference.rst
  docs/source/generated/nvcr.io-nvidia-merlin-merlin-tensorflow-training.rst
  docs/source/generated/nvcr.io-nvidia-merlin-merlin-training.rst
  docs/source/support_matrix/index.rst
  docs/source/toc.yaml
  docs/table_config.yaml
  docs/test_extractor.py
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/getting-started-movielens/imgs/gs-keras-model-plot.png
  examples/scaling-criteo/03-Training-with-TF.ipynb
  examples/scaling-criteo/imgs/keras-model-plot.png
  setup.cfg
  tests/unit/test_version.py
Labels: documentation

#308 chore: Add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: documentation

#327 Request that PRs are labeled
  CONTRIBUTING.md
Labels: chore

#325 Enable running the SMX data job in Blossom
  docs/README.md
  docs/extractor.py
  docs/requirements-doc.txt
  docs/test_extractor.py
Labels: chore

#329 Hand-edit the HugeCTR versions
  docs/data.json
Labels: documentation

#336 Remove entrypoint from inference/training images.
  docker/inference/dockerfile.ctr
  docker/inference/dockerfile.tf
  docker/inference/dockerfile.torch
  docker/training/dockerfile.ctr
  docker/training/dockerfile.tf
  docker/training/dockerfile.torch
Labels: bug
