Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-04, with the labels that each got.

#176 add basic tests
  tests/unit/__pycache__/test_version.cpython-38-pytest-7.1.0.pyc
  tests/unit/test_version.py
Labels: enhancement

#184 docs: Add redirect page
  .github/workflows/docs-sched-rebuild.yaml
Labels: documentation

#186 Update deploying multi-stage RecSys PoC nb
  examples/Deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  examples/Deploying-multi-stage-RecSys/README.md
  examples/PoC/README.md
Labels: documentation

#196 removed path from feast as updated in systems
  examples/Deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
Labels: bug

#215 Torch container horovod release version
  docker/training/dockerfile.torch
Labels: bug

#217 Add Arrow S3 support to the `tensorflow-training` container
  docker/training/dockerfile.tf
Labels: enhancement

#221 Install required packages for multi-stage notebooks using `%pip`
  examples/Deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
Labels: documentation

#247 Add a few Python and system packages for the example notebooks
  docker/dockerfile.merlin
Labels: bug

#252 Apply key rotation fixes to existing container Dockerfiles
  docker/inference/dockerfile.ctr
  docker/inference/dockerfile.tf
  docker/inference/dockerfile.torch
  docker/training/dockerfile.ctr
  docker/training/dockerfile.tf
  docker/training/dockerfile.torch
Labels: bug
