Repository NVIDIA-Merlin/Merlin, pull requests merged in 2022-10, with the labels that each got.

#637 fix: RMM and cuDF are no longer installed with pip
  docs/extractor.py
Labels: chore

#656 Upgrade upstream container references, get pyarrow from upstream
  docker/dockerfile.merlin
Labels: ci

#659 update TFDE build
  docker/dockerfile-nightly.merlin
  docker/dockerfile.tf
Labels: ci

#690 get numba from upstream container
  docker/dockerfile.merlin
Labels: bug, ci

#689 fix missing lib issue by adding from upstream
  docker/dockerfile.torch
Labels: bug, ci

#691 add llvmlite to base for numba dep
  docker/dockerfile.merlin
Labels: chore, ci, dependencies

#698 revert to 22.08
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: ci

#701 revert change from 2209 requirements
  docker/dockerfile.torch
Labels: ci

#705 Update for change of hugectr branch name
  docker/dockerfile-nightly.merlin
  docker/dockerfile.ctr
  docker/dockerfile.tf
  docker/ngc_overview_hugectr.md
  docker/ngc_overview_pytorch.md
  docker/ngc_overview_tensorflow.md
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
Labels: breaking, ci

#712 Install horovod in the ci-runner image for CI testing
  ci/dockerfile.ci
Labels: ci
