Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-07, with the labels that each got.

#1034 Moving systems examples to Merlin
  examples/ranking/README.md
  examples/ranking/tf/Training-and-Deploying-DLRM-model-with-Models-and-Systems.ipynb
  examples/traditional-ml/Serving-An-Implicit-Model-With-Merlin-Systems.ipynb
  examples/traditional-ml/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
  tests/integration/examples/test_serving_an_implicit_model_with_merlin_systems.py
  tests/integration/examples/test_serving_an_xgboost_model_with_merlin_systems.py
  tests/integration/examples/test_serving_ranking_models_with_merlin_systems.py
Labels: chore, examples

#1015 Creating integration tests for quick-start for ranking
  examples/quick_start/scripts/preproc/preprocessing.py
  tests/integration/examples/quick_start/test_preproc.py
  tests/integration/examples/quick_start/test_ranking.py
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: chore, unit-test

#1047 Pass a DataFrame to `setup_faiss` instead of array
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
Labels: chore

#1028 Move Next-Item-Prediction-with-Transformers examples from models
  examples/Next-Item-Prediction-with-Transformers/tf/transformers-next-item-prediction-with-pretrained-embeddings.ipynb
  examples/Next-Item-Prediction-with-Transformers/tf/transformers-next-item-prediction.ipynb
  pytest.ini
  tests/benchmark/test_asvdb_transformers_next_item_prediction.py
  tests/conftest.py
  tests/unit/test_transformers_next_item_prediction.py
  tests/unit/test_transformers_next_item_prediction_with_pretrained_embeddings.py
Labels: examples

#1022 updates notebooks for multistage with subgraphs
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: enhancement, chore

#1046 Update Documentation theme from `sphinx_rtd_theme` to `sphinx_book_theme`
  docs/requirements-doc.txt
  docs/source/_static/NVIDIA-LogoBlack.svg
  docs/source/_static/NVIDIA-LogoWhite.svg
  docs/source/_static/css/custom.css
  docs/source/_static/css/versions.css
  docs/source/_static/favicon.png
  docs/source/_static/js/rtd-version-switcher.js
  docs/source/_templates/layout.html
  docs/source/_templates/merlin-ecosystem.html
  docs/source/_templates/versions.html
  docs/source/conf.py
Labels: documentation

#1050 update link to training tutorial
  examples/traditional-ml/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
Labels: documentation

#1018 CTR dockerfile for 23.06
  docker/dockerfile.ctr
  docker/dockerfile.merlin
Labels: bug, ci

#1043 update dockerfile.tf and dockerfile.torch
  docker/dockerfile.tf
  docker/dockerfile.torch
Labels: ci

#1056 add package check for tests
  tests/unit/test_transformers_next_item_prediction.py
  tests/unit/test_transformers_next_item_prediction_with_pretrained_embeddings.py
Labels: bug, chore, ci

#1049 Enable cross-compiling for x86 + NVIDIA Grace (ARM64)
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: roadmap, chore
