Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-06, with the labels that each got.

#998 Add 23.05 changelog
  CHANGELOG.md
Labels: documentation

#999 split out multi gpu tests from single gpu
  .flake8
  .github/workflows/gpu-ci.yml
  pytest.ini
  tests/unit/examples/test_getting_started_hugectr.py
  tests/unit/examples/test_getting_started_pytorch.py
  tests/unit/examples/test_getting_started_tensorflow.py
  tests/unit/examples/test_scaling_criteo_merlin_models.py
  tests/unit/examples/test_scaling_criteo_merlin_models_hugectr.py
  tox.ini
Labels: chore, ci

#987 Copy tensorflow_estimator from DLFW
  ci/dockerfile.ci
Labels: ci, 23.05

#995 Build docs for stable branch and make default
  .github/workflows/docs-sched-rebuild.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docker/ngc_overview_hugectr.md
  docker/ngc_overview_pytorch.md
  docker/ngc_overview_tensorflow.md
  docs/README.md
  docs/source/conf.py
  docs/source/guide/recommender_models.rst
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/quick_start/ranking.md
  examples/quick_start/scripts/inference/README.md
  examples/quick_start/scripts/inference/inference.ipynb
  examples/quick_start/scripts/ranking/README.md
  examples/sagemaker-tensorflow/README.md
  examples/sagemaker-tensorflow/sagemaker-merlin-tensorflow.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/03-Training-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
Labels: documentation

#1003 Support matrix updates for 23.05
  docs/data.json
Labels: documentation

#1005 Add call to integration test script for Merlin Systems
  ci/container_integration.sh
Labels: ci

#1007 replace key before calling apt for anything
  ci/dockerfile.ci
Labels: ci

#1006 Update Integration test to get request from user_features instead of hard-coded value
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: chore

#1008 adding keyring permissions
  ci/dockerfile.ci
Labels: ci

#1011 removing keyring updates, uneeded now
  ci/dockerfile.ci
Labels: ci

#1013 add keyring update back
  ci/dockerfile.ci
Labels: ci

#1014 Improvements in Quick-start for Ranking
  examples/quick_start/__init__.py
  examples/quick_start/ranking.md
  examples/quick_start/scripts/__init__.py
  examples/quick_start/scripts/inference/__init__.py
  examples/quick_start/scripts/preproc/README.md
  examples/quick_start/scripts/preproc/__init__.py
  examples/quick_start/scripts/preproc/args_parsing.py
  examples/quick_start/scripts/preproc/preprocessing.py
  examples/quick_start/scripts/ranking/README.md
  examples/quick_start/scripts/ranking/__init__.py
  examples/quick_start/scripts/ranking/args_parsing.py
  examples/quick_start/scripts/ranking/cufile.log
  examples/quick_start/scripts/ranking/mtl.py
  examples/quick_start/scripts/ranking/ranking.py
Labels: enhancement

#1017 Fixed preprocessing and training scripts in Quick-start for Ranking
  examples/quick_start/scripts/preproc/preprocessing.py
  examples/quick_start/scripts/ranking/README.md
  examples/quick_start/scripts/ranking/ranking_models.py
Labels: bug

#1020 fix feast repo name in building-and-deploying-multi-stage-RecSys examples
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: chore, examples

#1031 activate cubinlinker lines in ci dockerfile
  ci/dockerfile.ci
Labels: ci

#1009 add changelog 23.06 structure
  CHANGELOG.md
Labels: documentation, skip-changelog

#1035 Support matrix updates for 23.06
  docs/data.json
Labels: documentation

#1037 Update README.md
  README.md
Labels: documentation

#1036 Update ci container
  ci/dockerfile.ci
Labels: bug, ci

#1038 ptx install using pip
  ci/dockerfile.ci
Labels: bug, ci
