Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-04, with the labels that each got.

#899 update version of cupy to be 12.0.0 minimum
  docker/dockerfile.merlin
Labels: bug, chore, ci

#901 Remove duplicate build image in base Dockerfile
  docker/dockerfile.merlin
Labels: chore, ci

#902 add TARGETARCH arg with default
  docker/dockerfile.merlin
Labels: chore, ci

#908 Don't install distributed embeddings by default, remove tests
  ci/container_unit.sh
  docker/dockerfile.tf
Labels: ci, 23.04

#909 remove software check for distributed embeddings
  ci/container_software.sh
  ci/container_unit.sh
Labels: chore, skip-changelog, ci

#911 Install comptabile version of protobuf in integration test
  ci/test_integration.sh
Labels: chore, ci, 23.04

#921 increase the size allowed for containers
  ci/container_size.sh
Labels: ci

#920 adding sympy to the torch container
  docker/dockerfile.torch
Labels: ci

#915 Quick-start for ranking with Merlin Models
  .gitignore
  examples/quick_start/README.md
  examples/quick_start/images/hpo_evolution_deepfm.png
  examples/quick_start/images/hpo_parallel_bars_deepfm.png
  examples/quick_start/images/most_important_hparams/mtl_mlp.png
  examples/quick_start/images/most_important_hparams/mtl_mmoe.png
  examples/quick_start/images/most_important_hparams/mtl_ple.png
  examples/quick_start/images/most_important_hparams/stl_dcn_click.png
  examples/quick_start/images/most_important_hparams/stl_deepfm_click.png
  examples/quick_start/images/most_important_hparams/stl_dlrm_click.png
  examples/quick_start/images/most_important_hparams/stl_mlp_click.png
  examples/quick_start/images/most_important_hparams/stl_wideanddeep_click.png
  examples/quick_start/images/mtl_benchmark.png
  examples/quick_start/images/quick_start_process.png
  examples/quick_start/images/stl_benchmark.png
  examples/quick_start/images/tenrec_dataset.png
  examples/quick_start/images/wandb_sweeps.png
  examples/quick_start/ranking.md
  examples/quick_start/requirements.txt
  examples/quick_start/scripts/preproc/README.md
  examples/quick_start/scripts/preproc/args_parsing.py
  examples/quick_start/scripts/preproc/preprocessing.py
  examples/quick_start/scripts/ranking/README.md
  examples/quick_start/scripts/ranking/args_parsing.py
  examples/quick_start/scripts/ranking/hypertuning/README.md
  examples/quick_start/scripts/ranking/hypertuning/tutorial_with_wb_sweeps.md
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/mtl_mlp/mtl_mlp-stage01.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/mtl_mlp/mtl_mlp-stage02.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/mtl_mmoe/mtl_mmoe-stage01.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/mtl_mmoe/mtl_mmoe-stage02.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/mtl_ple/mtl_ple-stage01.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/mtl_ple/mtl_ple-stage02.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dcn/stl_click_dcn.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dcn/stl_follow_dcn.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dcn/stl_like_dcn.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dcn/stl_share_dcn.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_deepfm/stl_click_deepfm.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dlrm/stl_click_dlrm.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dlrm/stl_follow_dlrm.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dlrm/stl_like_dlrm.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_dlrm/stl_share_dlrm.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_mlp/stl_click_mlp.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_mlp/stl_follow_mlp.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_mlp/stl_like_mlp.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_mlp/stl_share_mlp.yaml
  examples/quick_start/scripts/ranking/hypertuning/wandb_sweeps/stl_wide_n_deep/stl_click_wide_n_deep.yaml
  examples/quick_start/scripts/ranking/mtl.py
  examples/quick_start/scripts/ranking/ranking.py
  examples/quick_start/scripts/ranking/ranking_models.py
  examples/quick_start/scripts/ranking/run_logging.py
Labels: examples

#925 update the merlin dockerfile for container release
  docker/dockerfile.merlin
Labels: ci

#926 Update merlin dockerfile
  docker/dockerfile.merlin
Labels: ci

#938 remove arm64 support
  docker/dockerfile.merlin
Labels: ci
