Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-05, with the labels that each got.

#954 add 22.04 changelog
  CHANGELOG.md
Labels: documentation

#953 Add Recommender Model Guide
  docs/source/guide/imgs/models_ranking.png
  docs/source/guide/imgs/models_retrieval.png
  docs/source/guide/imgs/models_sequentialinteactions.png
  docs/source/guide/imgs/models_sessionbased.png
  docs/source/guide/recommender_models.rst
  docs/source/guide/recommender_system_guide.rst
  docs/source/toc.yaml
Labels: documentation

#963 don't re-run tests on closed PR
  .github/workflows/gpu-ci.yml
Labels: ci

#964 Update tag pattern in GitHub Workflows
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/release-drafter.yaml
Labels: ci

#965 Add workflows to check base branch and set stable branch
  .github/workflows/check-base-branch.yaml
  .github/workflows/set-stable-branch.yaml
Labels: ci

#939 Add `requirements.txt` that points to Merlin 23.04 releases
  requirements.txt
Labels: chore, ci, dependencies, 23.04

#967 Quick-start for Ranking: Fix bug when saving model trained with single task and moved util classes to Models
  examples/quick_start/scripts/ranking/ranking.py
  examples/quick_start/scripts/ranking/ranking_models.py
  examples/quick_start/scripts/ranking/run_logging.py
Labels: bug, enhancement

#976 Update merlin base to use triton/dlfw 23.03
  docker/dockerfile.merlin
Labels: ci, 23.05

#981 fix ci container to work with new environment
  ci/dockerfile.ci
Labels: ci

#979 Bump dask and pyarrow versions in integration test
  ci/test_integration.sh
Labels: chore, ci

#974 Update for new CUDA/arrow/parquet
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: chore, ci

#966 Quick start for Ranking - Include support for Triton inference
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/quick_start/ranking.md
  examples/quick_start/scripts/inference/README.md
  examples/quick_start/scripts/inference/args_parsing.py
  examples/quick_start/scripts/inference/inference.ipynb
  examples/quick_start/scripts/inference/inference.py
  examples/quick_start/scripts/preproc/args_parsing.py
  examples/quick_start/scripts/preproc/preprocessing.py
  examples/quick_start/scripts/ranking/README.md
  examples/quick_start/scripts/ranking/ranking.py
Labels: inference, examples

#982 WAR for hugectr gmock build error
  docker/dockerfile.ctr
Labels: bug, ci, 23.05

#984 downgrade protobuf after feast install
  ci/dockerfile.ci
Labels: ci

#975 Update feast to run on newest release version 0.31
  ci/test_integration.sh
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  requirements.txt
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: enhancement, chore

#985 Quick-start for ranking - Added --shuffled_train arg to ranking.py script
  examples/quick_start/scripts/ranking/README.md
  examples/quick_start/scripts/ranking/args_parsing.py
  examples/quick_start/scripts/ranking/ranking.py
Labels: enhancement

#988 update paths in deploying recsys example
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: bug, chore, ci

#990 syntax fix: use f-string
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: chore

#991 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci

#997 revert tensorflow install
  docker/dockerfile.tf
Labels: bug, ci
