Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-02, with the labels that each got.

#804 update README.md/docs
  examples/getting-started-movielens/README.md
Labels: documentation

#803 Fix docs build to use tox, as described
  .github/workflows/docs-build.yaml
  .github/workflows/docs-sched-rebuild.yaml
  docs/requirements-doc.txt
  tox.ini
Labels: chore

#789 Container size fix for <15gb
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
  docker/dockerfile.torch
Labels: chore, ci

#808 Use `--no-cache-dir` on all pip install commands in dockerfiles
  docker/dockerfile.merlin
  docker/dockerfile.tf
  docker/dockerfile.torch
Labels: ci

#812 clean up .git from cloned repos after installing
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: chore, ci

#817 Shallow Clone HugeCTR submodules and remove `.git/modules`
  docker/dockerfile.tf
Labels: ci

#821 fix syntax error
  docker/dockerfile.merlin
Labels: chore, ci

#830 Pin pynvml to 11.4.1
  docker/dockerfile.merlin
Labels: ci

#831 Remove NVT Triton back-end install from Docker base image
  docker/dockerfile.merlin
Labels: chore, ci

#832 Skip the container size check for the CI container
  ci/container_size.sh
  ci/container_software.sh
  ci/test_container.sh
Labels: chore, ci

#836 fix size check to exclude mounts
  ci/container_software.sh
Labels: ci, 23.02

#837 Consolidate size checks in container builds
  ci/container_size.sh
  ci/container_software.sh
Labels: chore, ci

#838 Fix string literal comparison in CI container test script
  ci/test_container.sh
Labels: chore, ci

#839 Adjust Merlin library installs in the nightly images
  docker/dockerfile-nightly.merlin
Labels: chore, ci

#840 Fix a variety of minor issues with the CI container build
  ci/dockerfile.ci
Labels: chore, ci

#841 Pin dask/distributed package versions after other installs in CI image
  ci/dockerfile.ci
Labels: chore, ci, 23.03

#843 Add transformers==4.26.1 to CI runner image
  ci/dockerfile.ci
Labels: ci
