Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-01, with the labels that each got.

#777 Install protobuf==3.20.3 for hugectr
  docker/dockerfile.ctr
Labels: ci

#786 Add legal statement to notebooks
  .pre-commit-config.yaml
  examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
  examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
  examples/getting-started-movielens/01-Download-Convert.ipynb
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/legacy/getting-started-movielens/01-Download-Convert.ipynb
  examples/legacy/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-TF.ipynb
  examples/legacy/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/legacy/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/legacy/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-TensorFlow.ipynb
  examples/legacy/multi-gpu-toy-example/multi-gpu_dask.ipynb
  examples/legacy/tensorflow/TFRecords-To-Parquet.ipynb
  examples/legacy/tensorflow/accelerating-tensorflow.ipynb
  examples/sagemaker-tensorflow/sagemaker-merlin-tensorflow.ipynb
  examples/scaling-criteo/01-Download-Convert.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/scaling-criteo/03-Training-with-HugeCTR.ipynb
  examples/scaling-criteo/03-Training-with-Merlin-Models-TensorFlow.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
Labels: documentation, skip-changelog

#779 Review getting started examples
  examples/getting-started-movielens/01-Download-Convert.ipynb
  examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  tests/unit/examples/test_getting_started_hugectr.py
  tests/unit/examples/test_getting_started_pytorch.py
  tests/unit/examples/test_getting_started_tensorflow.py
Labels: documentation, examples

#796 Update docs support README
  .gitignore
  docs/README.md
Labels: chore, skip-changelog

#802 add links to docs
  README.md
Labels: documentation
