Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-09, with the labels that each got.

#1068 Pull request/1065
  docker/dockerfile.ctr
  docker/dockerfile.torch
Labels: ci, 23.09

#1069 Pull request/1064
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: bug, 23.09

#1072 Remove the inference related test
  tests/unit/examples/test_getting_started_hugectr.py
Labels: enhancement, 23.09
