Repository NVIDIA-Merlin/Merlin, pull requests merged in 2023-03, with the labels that each got.

#783 Install hps backend and hps trt plugin in hugectr/tf/pytorch
  docker/dockerfile.ctr
  docker/dockerfile.merlin
  docker/dockerfile.tf
  docker/dockerfile.torch
Labels: chore, ci

#847 container size increase to 16gb
  ci/container_size.sh
Labels: chore, ci, 23.02

#859 Remove the legacy Getting Started With MovieLens example notebooks
  examples/legacy/getting-started-movielens/01-Download-Convert.ipynb
  examples/legacy/getting-started-movielens/02-ETL-with-NVTabular.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-HugeCTR.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/legacy/getting-started-movielens/03-Training-with-TF.ipynb
  examples/legacy/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/legacy/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/legacy/getting-started-movielens/README.md
  examples/legacy/getting-started-movielens/imgs/triton-tf.png
  examples/legacy/getting-started-movielens/inference-HugeCTR/.ipynb_checkpoints/Training-with-HugeCTR-checkpoint.ipynb
  tests/unit/examples/test_z_legacy_notebooks.py
Labels: chore

#864 Minor adjustments to the example notebooks and tests
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: bug

#849 Bump tensorflow version in ci-runner to 2.10
  ci/dockerfile.ci
Labels: ci

#860 Use 'scikit-learn' rather than 'sklearn' in ci-runner
  ci/dockerfile.ci
Labels: chore, ci

#846 Arm64 support in dockerfile.merlin
  docker/dockerfile.merlin
Labels: chore, ci

#855 Fix libnvinfer conflict
  docker/dockerfile.merlin
  docker/dockerfile.tf
Labels: chore, ci

#869 increase container size
  ci/container_size.sh
Labels: chore, ci, 23.03

#876 Update sok ut
  ci/container_software.sh
Labels: enhancement, chore, ci

#883 Install horovod 0.27 for tensorflow 2.11 support
  docker/dockerfile.tf
Labels: bug, chore, ci

#885 Update dependency versions in integration tests
  ci/test_integration.sh
  tests/integration/examples/test_ci_building_deploying_multi_stage_RecSys.py
Labels: chore, ci, 23.03

#890 Revert "Install horovod 0.27 for tensorflow 2.11 support (#883)"
  docker/dockerfile.tf
Labels: chore, ci, 23.03

#892 Replace nvtabular.utils with merlin.core.compat in criteo nvtabular n…
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
Labels: bug, 23.03

#891 Update unit tests to remove num_rows in read_parquet()
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-Merlin-Models-TensorFlow.ipynb
  tests/unit/examples/test_building_deploying_multi_stage_RecSys.py
Labels: chore, ci, 23.03
